name: Eduwide
description: "HNDIT 4232 Project - Login Portal"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5

  intl: ^0.19.0

  timezone: ^0.9.2

  image_picker: ^1.0.4
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/app-icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/app-icon.png"

  assets:
    - assets/logo/logo.png
    - assets/logo/app-icon.png
